theme = "acme"

[editor]
auto-pairs = true
line-number = "absolute"
middle-click-paste = true
idle-timeout = 0

[editor.statusline]
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

left = ["spinner", "file-modification-indicator", "mode"]
center = ["read-only-indicator", "file-name", "version-control"]
right = ["diagnostics", "register", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true
character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = false

[editor.smart-tab]
enable = false

[editor.soft-wrap]
enable = true
